In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [2]:
df = pd.read_csv("Iris.csv")

# Display first rows
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [3]:
# Drop unnecessary column (if exists)
if 'Id' in df.columns:
    df = df.drop('Id', axis=1)

# Features and Target
X = df.drop('Species', axis=1)
y = df['Species']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [5]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [6]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [7]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9777777777777777


In [8]:
error_rate = 1 - accuracy
print("Error Rate:", error_rate)

Error Rate: 0.022222222222222254


In [9]:
precision = precision_score(y_test, y_pred, average='macro')
print("Precision:", precision)

Precision: 0.9761904761904763


In [10]:
recall = recall_score(y_test, y_pred, average='macro')
print("Recall:", recall)

Recall: 0.9743589743589745


In [11]:
for i in range(len(cm)):
    TP = cm[i][i]
    FP = sum(cm[:, i]) - TP
    FN = sum(cm[i, :]) - TP
    TN = cm.sum() - (TP + FP + FN)

    print(f"\nClass {i}:")
    print("TP:", TP)
    print("FP:", FP)
    print("FN:", FN)
    print("TN:", TN)


Class 0:
TP: 19
FP: 0
FN: 0
TN: 26

Class 1:
TP: 12
FP: 0
FN: 1
TN: 32

Class 2:
TP: 13
FP: 1
FN: 0
TN: 31
